<?php
/**
 * MyBB 1.6 English Language Pack
 * Copyright 2010 MyBB Group, All Rights Reserved
 * 
 * $Id$
 */

$l['nav_online'] = "WHOZ HERE";
$l['nav_onlinetoday'] = "WHOZ WUZ HERE";

$l['viewing_announcements'] = "LOOKIN AT THIS ANNOUNCEMENT: <a href=\"{1}\">{2}</a>";
$l['viewing_announcements2'] = "LOOKIN AT ANNOUNCEMENT";
$l['viewing_attachment'] = "LOOKIN AT ATTACHMENT";
$l['viewing_attachment2'] = "LOOKIN AT <a href=\"attachment.php?aid={1}\" target=\"_blank\">ATTACHMENT</a> IN THRED <a href=\"{3}\">{2}</a>";
$l['viewing_calendar'] = "LOOKIN AT <a href=\"calendar.php\">CALENDER</a>";
$l['viewing_event'] = "LOOKIN AT EVENT";
$l['viewing_event2'] = "LOOKIN AT THIS EVENT: <a href=\"{1}\">{2}</a>";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\">ADDIN EVENT</a>";
$l['editing_event'] = "CHANGIN EVENT";
$l['editing_post'] = "CHANGIN POST";
$l['viewing_forum'] = "LOOKIN AT FORUM";
$l['viewing_forum2'] = "LOOKIN AT THIS FORUM: <a href=\"{1}\">{2}</a>";
$l['forum_redirect_to'] = "UR BEIN SENT TO <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "{1} <a href=\"index.php\">IN UR INDEX</a>";
$l['activating_account'] = "ACTIVATIN ACCOUNT";
$l['viewing_profile'] = "LOOKIN AT PROFILE";
$l['viewing_profile2'] = "STALKIN <a href=\"{1}\">{2}</a>";
$l['registering'] = "<a href=\"member.php?action=register\">JOININ</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">LOGGIN IN</a>";
$l['logging_in_plain'] = "LOGGIN IN";
$l['logging_out'] = "SAYIN BAI";
$l['emailing_user'] = "WRITIN TO A USR";
$l['rating_user'] = "RATIN A USR";
$l['viewing_memberlist'] = "LOOKIN AT <a href=\"memberlist.php\">TEH MEMBERS</a>";
$l['viewing_whoposted'] = "LOOKIN AT THE POSTERS";
$l['viewing_whoposted2'] = "LOOKIN AT THE POSTERS IN <a href=\"{1}\">{2}</a>";
$l['marking_read'] = "<a href=\"misc.php?action=markread&amp;my_post_key={1}\">SAYIN FORUMS IZ READ</a>";
$l['viewing_helpdocs'] = "LOOKIN AT <a href=\"misc.php?action=help\">TEH HELP DOCS</a>";
$l['viewing_buddylist'] = "LOOKIN AT <a href=\"misc.php?action=buddypopup\">THEIR FRENDS</a>";
$l['viewing_smilies'] = "LOOKIN AT <a href=\"misc.php?action=smilies\">TEH SMILIES</a>";
$l['viewing_syndication'] = "LOOKIN AT <a href=\"misc.php?action=syndication\">TEH RSS</a> PAGE";
$l['replying_thread'] = "POSTIN TO A THRED";
$l['replying_thread2'] = "POSTIN TO <a href=\"{1}\">{2}</a>";
$l['posting_thread'] = "MAKIN A THRED";
$l['posting_thread2'] = "MAKIN A THRED IN <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "LOOKIN AT <a href=\"online.php\">WHOZ HERE</a>";
$l['viewing_woltoday'] = "LOOKIN AT <a href=\"online.php?action=today\">WHO WUZ HERE</a>";
$l['creating_poll'] = "MAKIN A POLL";
$l['editing_poll'] = "CHANGIN A POLL";
$l['viewing_pollresults'] = "LOOKIN AT A POLL";
$l['voting_poll'] = "VOTIN IN A POLL";
$l['using_modtools'] = "USIN MOD'S TOOLS";
$l['sending_pm'] = "SENDIN MAILZ";
$l['reading_pm'] = "READIN MAILZ";
$l['editing_pmfolders'] = "CHANGIN MAILZ BOXEZ";
$l['using_pmsystem'] = "USIN TEH MAILZ";
$l['reporting_post'] = "TATTLIN ON SUMONE";
$l['searching_forum'] = "<a href=\"search.php\">SERCHIN</a> {1}";
$l['reading_thread'] = "READIN THRED";
$l['reading_thread2'] = "READIN THIS: <a href=\"{1}\">{2}</a> {3}";
$l['viewing_team'] = "LOOKIN AT TEH TEAM";
$l['viewing_stats'] = "LOOKIN AT TEH STATS";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">CHANGIN PROFILE</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">CHANGIN OPSHUNZ</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">CHANGIN SIGNATUR</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">CHANGIN AVATAR</a>";
$l['viewing_subscriptions'] = "Viewing <a href=\"usercp.php?action=subscriptions\">Thread Subscriptions</a>";
$l['viewing_favorites'] = "LOOKIN AT <a href=\"usercp.php?action=favorites\">FAV THREDS</a>";
$l['editing_pad'] = "CHANGIN <a href=\"usercp.php?action=notepad\">THEIR NOTES</a>";
$l['editing_password'] = "CHANGIN <a href=\"usercp.php?action=password\">PASSWURD</a>";
$l['user_cp'] = "Viewing <a href=\"usercp.php\">User Control Panel</a>";
$l['viewing_portal'] = "Viewing <a href=\"portal.php\">Portal</a> Page";
$l['viewing_noperms'] = "Viewing No Permissions Page";
$l['unknown_location'] = "<a href=\"{1}\">Unknown Location</a>";
$l['giving_reputation'] = "Giving Reputation to <a href=\"{1}\">{2}</a>";
$l['viewing_reputation_report'] = "Viewing <a href=\"{1}\">{2}'s Reputation</a>";
$l['viewing_reputation_report2'] = "Viewing Reputation";
$l['member_resendactivation'] = "Resending Account Activation Email";
$l['member_lostpw'] = "Retrieving <a href=\"member.php?action=lostpw\">Lost Password</a>";
$l['sending_thread'] = "Sending a thread to a friend";
$l['guest'] = "Guest";
$l['page'] = "Page";
$l['users_online'] = "WHOZ HERE";
$l['on_username'] = "Username";
$l['time'] = "Time";
$l['location'] = "Location";
$l['online_today'] = "WHO WUZ HERE";
$l['refresh_page'] = "Refresh this Page";
$l['online_online_plural'] = "users";
$l['online_online_singular'] = "user";
$l['online_member_plural'] = "members";
$l['online_member_singular'] = "member";
$l['online_anon_plural'] = "are";
$l['online_anon_singular'] = "is";
$l['online_guest_plural'] = "guests";
$l['online_guest_singular'] = "guest";
$l['online_count'] = "{1} {2} active in the past {3} minutes ({4} {5}, {6} of whom {7} invisible, and {8} {9}).";
$l['ip'] = "IP:";
$l['resolves_to'] = "Host Name:";
$l['if_resolvable'] = "(if resolvable)";
$l['admin_options'] = "Admin Options:";
$l['search_regip_users'] = "Search for users who have registered with this IP";
$l['search_postip_users'] = "Search for users who have posted with this IP";
$l['lookup'] = "[lookup]";
$l['member_online_today'] = "<strong>1</strong> Member Was Online Today";
$l['members_were_online_today'] = "<strong>{1}</strong> Members Were Online Today";
$l['member_online_hidden'] = " ({1} member was invisible)";
$l['members_online_hidden'] = " ({1} members were invisible)";
$l['rating_thread'] = "Rating thread";
$l['viewing_imcenter'] = "Viewing IM Center";
$l['managing_favorites'] = "Managing Favorite Threads";
$l['managing_subscriptions'] = "Managing Subscribed Threads";
$l['managing_group'] = "Managing a User Group";
$l['viewing_modcp'] = "Viewing Moderator CP";
$l['viewing_modlogs'] = "Viewing Moderator Logs";
$l['managing_announcements'] = "Managing Announcements";
$l['search_for_user'] = "Searching for users";
$l['managing_warninglogs'] = "Managing Warning Logs";
$l['searching_ips'] = "Searching IPs";
$l['viewing_reports'] = "Viewing Reported Posts";
$l['adding_announcement'] = "Adding an Announcement";
$l['deleting_announcement'] = "Deleting an Announcement";
$l['editing_announcement'] = "Editing an Announcement";
$l['managing_modqueue'] = "Managing Moderation Queue";
$l['editing_user_profiles'] = "Editing User Profiles";
$l['managing_bans'] = "Managing Bans";
$l['revoking_warning'] = "Revoking a warning";
$l['warning_user'] = "Warning a user";
$l['viewing_warning'] = "LOOKIN AT A WARNING";
$l['managing_warnings'] = "Managing warnings";
$l['changing_dst'] = "Changing DST Switch";
$l['printing_thread'] = "Printing a Thread";
$l['printing_thread2'] = "Printing Thread <a href=\"{1}\">{2}</a>";
$l['managing_buddyignorelist'] = "Managing Buddy/Ignore List";
?>